---
- hosts: zookeeper
  remote_user: root
  tasks:
      - command: /home/ubuntu/zookeeper-3.4.6/bin/zkServer.sh start

- hosts: nimbus
  remote_user: root
  tasks:
    - command: /home/ubuntu/apache-storm-0.9.4/bin/storm nimbus
      poll: 0
      async: 600
- hosts: supervisor
  remote_user: root
  tasks:
    - command: /home/ubuntu/apache-storm-0.9.4/bin/storm supervisor
      poll: 0
      async: 600
- hosts: nimbus
  remote_user: root
  tasks:
    - command: /home/ubuntu/apache-storm-0.9.4/bin/storm ui
      poll: 0
      async: 600

